### ISSUE TITLE
[Too Many Issues] - [Marvel] CMRO Core Reading Order-Part 01.cbl

### ISSUE THREAD

**Issue by muhguh** [DieselTech/CBL-ReadingLists#74]
**Let us know what issues are extra**
CMRO Core 1 has 6 duplicate books. These 6 appear in the list twice:

**The List:**
```
<Book Series="Journey into Mystery" Number="119" Volume="1952" Year="1965">
<Database Name="cv" Series="1497" Issue="7962" />
</Book>
<Book Series="Journey into Mystery" Number="120" Volume="1952" Year="1965">
<Database Name="cv" Series="1497" Issue="8031" />
</Book>
<Book Series="Journey into Mystery" Number="121" Volume="1952" Year="1965">
<Database Name="cv" Series="1497" Issue="8104" />
</Book>
<Book Series="Journey into Mystery" Number="123" Volume="1952" Year="1965">
<Database Name="cv" Series="1497" Issue="8232" />
</Book>
<Book Series="Journey into Mystery" Number="124" Volume="1952" Year="1966">
<Database Name="cv" Series="1497" Issue="8309" />
</Book>
<Book Series="Journey into Mystery" Number="125" Volume="1952" Year="1966">
<Database Name="cv" Series="1497" Issue="8369" />
</Book>
```

**Additional context**
I can make a pull request to remove these 6 but that would leave the list at 994 items instead of 1000. 
The proper fix I suppose would be to shift everything and change all of the core lists.

**Comment by flips22** [comment]
Thanks for the catch.  this comes from how cmro does story A and story B.  There could be more, I need to look for duplicate lines in the other lists as well.  Another day..  :)  I think the best situation is to have one list with 994 issues instead of updating all the lists so they all have exactly 1000 books.  That would cause everyone to have to update all of their lists even though the content didn't change on all but the first list..
